### ISSUE TITLE
Build USB problem

### ISSUE THREAD

**Issue by delanolima** [xps3riments/localSTORE#3]
I click "Build USB" and just a "package_link.xml" is created in my pendrive. So I can't install it.

**Comment by xperiments** [comment]
Have you read the changelog? XD

Menu is moved to "Package Manager", there is no more need to install anything... only usb generation... that's all..

**Comment by delanolima** [comment]
Hmmm... But nothing has changed in my "Package Manager". It doesn't have the localStore menu. I will try to uninstall everything from version 1.0.0 to see what happens.

**Comment by delanolima** [comment]
I removed the files modified by version 1.0.0 and now the localStore is in the Package Manager.

In my opinion the store looks more beautiful in the game menu as it was in version 1.0.0 or if you prefer it in the Package Manager, maybe it gets more organized by locating it with submenu.

Congratulations!!!

**Comment by ThunderDOPE** [comment]
Hello.

I'm stuck at this, can you teach me how do you remove de 1.0.0 files?

**Comment by delanolima** [comment]
Hi, @ThunderDOPE!

Yes, I can. The localStore install two files in the HDD:
dev_blind\vsh\resource\explore\icon\hen_enable.png
dev_blind\vsh\resource\explore\xmb\category_game.xml

I suggest you get these files from the HEN installer.

**Comment by ThunderDOPE** [comment]
I used managunz fileexplorer to delet those files. Now my ps3 wont even turn on...
it is asking for a system update by usb. Guess i'm just stupid

**Comment by delanolima** [comment]
@ThunderDOPE, you had to replace the files with the "original" HEN files. So I made the suggestion for you to get the files from the HEN installer.

You need to download the latest update from Sony's official website and reinstall the firmware from a flash drive.

**Comment by ThunderDOPE** [comment]
Thanks, I got it working now.

It's actually not that hard, my bad.

**Comment by delanolima** [comment]
Nice!!

Be careful when modifying anything on dev_blind or dev_flashx (do not touch that), as it can brick your console.

**Comment by xperiments** [comment]
Great... I need to see how HEN will change and then take a decision about the Menu.

The main problem of the menu "at root" is that on every HEN update we need to update the menu...

If it resides on usb there is not this problem...

Anyway, maybe next version...

**Comment by xps3riments** [comment]
Great... I need to see how HEN will change and then take a decision about the Menu.

The main problem of the menu "at root" is that on every HEN update we need to update the menu...

If it resides on usb there is not this problem...

Anyway, maybe next version...
